language: c

sudo: false

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev	
    - r-recommended
    - texlive-full
    - unixodbc-dev
    - libcurl4-openssl-dev

cache:
  directories:
    - ~/Rlib
    - $HOME/bin

before_install:
  - export PATH=$HOME/bin:$PATH
  - chmod 755 .push_gh_pages.sh
  - chmod 755 ghgenerate.R

install:
  - mkdir -p ~/Rlib
  - mkdir -p $HOME/bin
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'

script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran 

after_success:
  - ./.push_gh_pages.sh
