language: r
sudo: required
warnings_are_errors: false

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages:
 - Rdatatable/data.table
 
notifications:
  email:
    on_success: stephanie.g.locke@gmail.com
    on_failure: stephanie.g.locke@gmail.com

before_install:
  - chmod 755 ./.push_gh_pages.sh
  - chmod 755 ./ghgenerate.R
  
after_success:
  - ./.push_gh_pages.sh
